services:
  app:
    image: ahmadrafii07/webujikom:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bengkel-app-1
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: bengkel_mobil
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - uji-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bengkel_mobil
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - uji-net

  nginx:
    image: nginx:latest
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Pastikan nama file .crt dan .key sudah sesuai dengan domain bengkelrapii.com
      - ./ssl/bengkel.crt:/etc/nginx/ssl/bengkel.crt:ro
      - ./ssl/bengkel.key:/etc/nginx/ssl/bengkel.key:ro
    networks:
      - uji-net

networks:
  uji-net:
    driver: bridge

volumes:
  dbdata:
